[build]
publish = "storage/app/static"
command = "./build.sh"

[build.environment]
PHP_VERSION = "7.4"
NPM_VERSION = "7.6.3"
NODE_VERSION = "14.16.0"
NODE_ENV = "production"
APP_URL = "https://www.threedots.ca"
PUBLIC_DIR = "storage/app/static"

[[headers]]
for = "/feed"
[headers.value]
Content-Type = "application/atom+xml"

[[headers]]
for = "/fonts/*"
[header.value]
Cache-Control = '''
public,
immutable,
max-age=2592000'''
