[build]
publish = "storage/app/static"
command = "./build.sh"

[build.environment]
PHP_VERSION = "8.4"
PNPM_VERSION = "9.1.2"
NODE_VERSION = "21"
NODE_ENV = "production"
APP_ENV = "production"
APP_URL = "https://www.threedots.ca"
APP_DEBUG = "false"
PUBLIC_DIR = "storage/app/static"

[[headers]]
for = "/feed"
[headers.values]
Content-Type = "application/atom+xml"

[[headers]]
for = "/assets/*"
[headers.values]
Cache-Control = '''
public
immutable
max-age=2592000'''

[[headers]]
for = "/build/*"
[headers.values]
Cache-Control = '''
public
immutable
max-age=2592000'''
