[build]
publish = "storage/app/static"
command = "./build.sh"

[build.environment]
PHP_VERSION = "7.4"
NPM_VERSION = "8.5.2"
NODE_VERSION = "16"
NODE_ENV = "production"
APP_URL = "https://www.threedots.ca"
PUBLIC_DIR = "storage/app/static"

[[headers]]
for = "/feed"
[headers.values]
Content-Type = "application/atom+xml"

[[headers]]
for = "/assets/*"
[headers.values]
Cache-Control = '''
public
immutable
max-age=2592000'''
