title: Ellipses
content:
  -
    type: paragraph
    content:
      -
        type: text
        text: 'Although to us, owing to their typically small size, they all look the same, in reality it''s not so: every ellipsis is unique. The examples below have been magnified several hundred times, so that you can examine their diverse characteristics.'
description: 'A selection of ellipses, magnified so that they are readable, and ordered by date of discovery.'
updated_by: ef566878-06e2-4591-9b05-2130076004d2
updated_at: 1615081993
blueprint: marks
