title: Semicolons
content:
  -
    type: paragraph
    content:
      -
        type: text
        text: 'But what is there to say about the semicolon?'
description: 'The semicolon! Too elegant, by far, for a medium that does not involve paper.'
updated_by: ef566878-06e2-4591-9b05-2130076004d2
updated_at: 1615081146
blueprint: marks
